# Generated by Django 3.2.11 on 2022-07-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sensor name')),
                ('humidity', models.CharField(blank=True, max_length=250, null=True, verbose_name='Humidity value')),
                ('temp', models.CharField(blank=True, max_length=250, null=True, verbose_name='Temperature value')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Latitude coordinates')),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Longitude coordinates')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
